#100 UNIQUE GOOD RECOMMENDATIONS 
insert into imdb_ijs.movies_recommendations values ('291698', '210511', 10, 'liagolding', 'Both films are psychological crime thrillers that require intense analytical thinking. Viewers who enjoy the dark, investigative progression of Se7en will find Mementos rewarding.', null); -- Se7en -> Memento
insert into imdb_ijs.movies_recommendations values ('210511', '123435', 9, 'liagolding', 'analytical plots and unexpected final twists.', null); -- Memento -> The Game
insert into imdb_ijs.movies_recommendations values ('112290', '350424', 9, 'liagolding', 'These are heavy psychological dramas. If you appreciate Fight Clubs dark mental twists, Vanilla Sky offers a parallel experience with a tragic undertone.', null); -- Fight Club -> Vanilla Sky
insert into imdb_ijs.movies_recommendations values ('131780', '209158', 10, 'liagolding', 'A pairing of Martin Scorseses legendary crime chronicles with authentic character analysis.', null); -- Goodfellas -> Mean Streets
insert into imdb_ijs.movies_recommendations values ('209158', '56304', 9, 'liagolding', 'Both are realistic crime drama, complex editing, and deep characters.', null); -- Mean Streets -> Casino
insert into imdb_ijs.movies_recommendations values ('267038', '276217', 10, 'liagolding', 'Quentin Tarantinos 90s crime masterpieces with crime dynamic, and character drama.', null); -- Pulp Fiction -> Reservoir Dogs
insert into imdb_ijs.movies_recommendations values ('276217', '306032', 9, 'liagolding', 'high-energy crime thrillers and multi-character puzzle.', null); -- Reservoir Dogs -> Snatch.
insert into imdb_ijs.movies_recommendations values ('123435', '247579', 9, 'liagolding', 'Both thrillers focus on high-tech systems and survival strategies.', null); -- The Game -> Panic Room
insert into imdb_ijs.movies_recommendations values ('247579', '160524', 8, 'liagolding', 'Intense Hollywood thrillers built around isolation and psychological stress.', null); -- Panic Room -> Insomnia
insert into imdb_ijs.movies_recommendations values ('397121', '214755', 9, 'liagolding', 'Both are thrillers that transcend mindless action and complex logical puzzles regarding human destiny and free will.', null); -- Matrix -> Minority Report
insert into imdb_ijs.movies_recommendations values ('214755', '40199', 9, 'liagolding', 'Shares a direct lineage of Philip K. Dick inspired neo-noir detective sci-fi.', null); -- Minority Report -> Blade Runner
insert into imdb_ijs.movies_recommendations values ('326155', '209158', 9, 'liagolding', 'Captures the dark realistic urban decay of 1970s New York under Martin Scorseses direction.', null); -- Taxi Driver -> Mean Streets
insert into imdb_ijs.movies_recommendations values ('297838', '290070', 10, 'liagolding', 'Both historical dramas dealing with survival inside oppressive institutions.', null); -- Shawshank Redemption -> Schindler's List
insert into imdb_ijs.movies_recommendations values ('290070', '289109', 10, 'liagolding', 'Both intense historical records of World War II.', null); -- Schindler's List -> Saving Private Ryan
insert into imdb_ijs.movies_recommendations values ('379331', '405119', 8, 'liagolding', 'Both classical detective fiction with traditional investigative puzzles.', null); -- Sherlock Holmes 1984 -> Sherlock Holmes 1951
insert into imdb_ijs.movies_recommendations values ('405119', '263076', 8, 'liagolding', 'Both narratives feature a methodical, sharp investigator breaking down mystory.', null); -- Sherlock Holmes 1951 -> Prescription for Murder
insert into imdb_ijs.movies_recommendations values ('238072', '306032', 9, 'liagolding', 'Both thriller with memorable character networks.', null); -- Ocean's Eleven -> Snatch.
insert into imdb_ijs.movies_recommendations values ('300229', '300230', 9, 'liagolding', 'Both are comedic sequel that maintains the sharp wit.', null); -- Shrek -> Shrek 2
insert into imdb_ijs.movies_recommendations values ('271095', '159172', 9, 'liagolding', 'Both films are clever historical puzzles.', null); -- Raiders of the Lost Ark -> Indiana Jones 3
insert into imdb_ijs.movies_recommendations values ('113506', '328272', 8, 'liagolding', 'Grounded, deeply moving Hollywood dramas featuring premier star performances.', null); -- Finding Neverland -> The Terminal
insert into imdb_ijs.movies_recommendations values ('291698', '233058', 8, 'liagolding', 'Both movies are dark mysteries where the main character must investigate a complex, scary puzzle.', null); -- Se7en -> The Ninth Gate
insert into imdb_ijs.movies_recommendations values ('210511', '268034', 8, 'liagolding', 'Perfect for audiences who love analytical plots, mystery, and trying to solve a puzzle.', null); -- Memento -> The Puzzle
insert into imdb_ijs.movies_recommendations values ('267038', '164572', 9, 'liagolding', 'Both are clever crime movies directed by Quentin Tarantino with witty writing and deep character analysis.', null); -- Pulp Fiction -> Jackie Brown
insert into imdb_ijs.movies_recommendations values ('131780', '56304', 10, 'liagolding', 'Both are realistic crime dramas directed by Martin Scorsese with Hollywood stars and great strategy.', null); -- Goodfellas -> Casino
insert into imdb_ijs.movies_recommendations values ('238072', '118367', 8, 'liagolding', 'Both movies feature a large cast of Hollywood stars and use very clever humor and witty dialogue.', null); -- Ocean's Eleven -> Four Rooms
insert into imdb_ijs.movies_recommendations values ('312170', '130953', 9, 'liagolding', 'Both are classic action spy movies with mystery, clever plots, and iconic Hollywood style.', null); -- Spy Who Loved Me -> Goldfinger
insert into imdb_ijs.movies_recommendations values ('130953', '159172', 9, 'liagolding', 'Both are great classic action adventure movies with smart strategies and very witty dialogue.', null); -- Goldfinger -> Indiana Jones 3
insert into imdb_ijs.movies_recommendations values ('300229', '311604', 8, 'liagolding', 'Both animated titles feature clever pop-culture parodies and unique humor for mature audiences.', null); -- Shrek -> SpongeBob Legend Spatula
insert into imdb_ijs.movies_recommendations values ('40199', '214755', 9, 'liagolding', 'Both are smart sci-fi thrillers focused on detective work and logical puzzles in the future.', null); -- Blade Runner -> Minority Report
insert into imdb_ijs.movies_recommendations values ('123849', '46169', 9, 'liagolding', 'Both are epic historical dramas grounded in reality with deep character analysis and sad endings.', null); -- Gangs of New York -> Braveheart
insert into imdb_ijs.movies_recommendations values ('330670', '297838', 9, 'liagolding', 'Both are high-quality realistic psychological dramas with excellent Hollywood stars and character analysis.', null); -- This Boy's Life -> Shawshank Redemption
insert into imdb_ijs.movies_recommendations values ('350424', '123435', 8, 'liagolding', 'Both are psychological thrillers with smart plots that keep you thinking until the final twist.', null); -- Vanilla Sky -> The Game
insert into imdb_ijs.movies_recommendations values ('271095', '131885', 8, 'liagolding', 'Both are classic adventure movies with clever puzzles, strategies, and famous Hollywood writers.', null); -- Raiders of the Lost Ark -> The Goonies
insert into imdb_ijs.movies_recommendations values ('131885', '159172', 9, 'liagolding', 'Great classic adventure films that combine a smart mystery with witty writing and family dynamics.', null); -- The Goonies -> Indiana Jones 3
insert into imdb_ijs.movies_recommendations values ('41518', '131780', 9, 'liagolding', 'Both are realistic crime biographies about the rise and fall of a criminal empire.', null); -- Blow -> Goodfellas
insert into imdb_ijs.movies_recommendations values ('56871', '41518', 8, 'liagolding', 'Both are real history crime dramas about a smart strategist chased by federal agents.', null); -- Catch Me If You Can -> Blow
insert into imdb_ijs.movies_recommendations values ('165961', '271095', 9, 'liagolding', 'Both are classic Hollywood thrillers directed by Steven Spielberg with great pacing and tension.', null); -- Jaws -> Raiders of the Lost Ark
insert into imdb_ijs.movies_recommendations values ('10702', '330670', 8, 'liagolding', 'Both are realistic psychological dramas about family struggles directed by Martin Scorsese or starring top actors.', null); -- Alice Doesnt Live Here -> This Boy's Life
insert into imdb_ijs.movies_recommendations values ('188507', '165961', 8, 'liagolding', 'Both are classic action thrillers grounded in reality with memorable characters and high tension.', null); -- Lethal Weapon -> Jaws
insert into imdb_ijs.movies_recommendations values ('283410', '263360', 9, 'liagolding', 'Both are grounded comedies starring the same Hollywood stars with very witty writing.', null); -- Runaway Bride -> Pretty Woman
insert into imdb_ijs.movies_recommendations values ('185628', '129185', 9, 'liagolding', 'Both are epic historical dramas with a lonely hero, deep strategies, and a sad ending.', null); -- Last Samurai -> Gladiator
insert into imdb_ijs.movies_recommendations values ('56304', '276217', 9, 'liagolding', 'Both are intense crime dramas focused on professional criminals, strategy, and realistic tension.', null); -- Casino -> Reservoir Dogs
insert into imdb_ijs.movies_recommendations values ('25192', '56871', 9, 'liagolding', 'Both are smart biographies about famous historical figures with excellent character analysis and star power.', null); -- Aviator, The -> Catch Me If You Can
insert into imdb_ijs.movies_recommendations values ('66194', '644', 9, 'liagolding', 'Both are clever teen comedies with very witty dialogue that are grounded in reality.', null); -- Clueless -> 10 Things I Hate About You
insert into imdb_ijs.movies_recommendations values ('30686', '330670', 9, 'liagolding', 'Both are intense psychological dramas about youth struggles starring a young Leonardo DiCaprio.', null); -- Basketball Diaries -> This Boy's Life
insert into imdb_ijs.movies_recommendations values ('247579', '165961', 8, 'liagolding', 'Both are realistic, high-tension thrillers about characters trapped in a dangerous situation.', null); -- Panic Room -> Jaws
insert into imdb_ijs.movies_recommendations values ('21213', '40199', 8, 'liagolding', 'Both are smart sci-fi dramas with logical depth that explore human emotions and technology.', null); -- AI -> Blade Runner
insert into imdb_ijs.movies_recommendations values ('8183', '333856', 8, 'liagolding', 'Both are high-prestige period dramas focusing on intense relationships and societal constraints.', null); -- Age of Innocence -> Titanic
insert into imdb_ijs.movies_recommendations values ('159175', '159172', 9, 'liagolding', 'Classic action adventure movies from the same series with historical puzzles and clever strategy.', null); -- Indiana Jones 2 -> Indiana Jones 3
insert into imdb_ijs.movies_recommendations values ('181766', '185704', 8, 'liagolding', 'Both are deep historical dramas directed by Martin Scorsese with complex character analysis.', null); -- Kundun -> Last Temptation of Christ
insert into imdb_ijs.movies_recommendations values ('253010', '297838', 9, 'liagolding', 'Both are grounded crime dramas about escape and survival with deep character breakdowns.', null); -- Perfect World, A -> Shawshank Redemption
insert into imdb_ijs.movies_recommendations values ('47130', '326155', 9, 'liagolding', 'Both are dark psychological dramas directed by Martin Scorsese taking place in New York.', null); -- Bringing Out the Dead -> Taxi Driver
insert into imdb_ijs.movies_recommendations values ('256839', '214755', 8, 'liagolding', 'Both are smart sci-fi thrillers that use logical tracking strategies and have high tension.', null); -- Pitch Black -> Minority Report
insert into imdb_ijs.movies_recommendations values ('39551', '289109', 9, 'liagolding', 'Both are realistic war dramas that focus on tactical military missions and personal sacrifice.', null); -- Black Hawk Down -> Saving Private Ryan
insert into imdb_ijs.movies_recommendations values ('67388', '131780', 8, 'liagolding', 'Both are realistic dramas about a mentor teaching a younger character the rules of a dangerous game.', null); -- Color of Money -> Goodfellas
insert into imdb_ijs.movies_recommendations values ('7842', '267038', 9, 'liagolding', 'Both are smart comedies with unique, non-linear criminal plots and very witty writing.', null); -- After Hours -> Pulp Fiction
insert into imdb_ijs.movies_recommendations values ('54209', '291698', 9, 'liagolding', 'Both are intense psychological thrillers with a dark atmosphere and a brilliant crime plot.', null); -- Cape Fear -> Se7en
insert into imdb_ijs.movies_recommendations values ('20253', '34104', 8, 'liagolding', 'Both are unique Hollywood dramas starring Johnny Depp with deep character analysis.', null); -- Arizona Dream -> Benny & Joon
insert into imdb_ijs.movies_recommendations values ('45312', '209158', 8, 'liagolding', 'Early classic crime dramas directed by Martin Scorsese with a realistic, gritty atmosphere.', null); -- Boxcar Bertha -> Mean Streets
insert into imdb_ijs.movies_recommendations values ('34104', '62460', 8, 'liagolding', 'Both are grounded Hollywood dramas with clever humor, famous stars, and unique relationships.', null); -- Benny & Joon -> Chocolat
insert into imdb_ijs.movies_recommendations values ('46167', '46169', 8, 'liagolding', 'Both are serious dramatic films focusing on personal sacrifice, honor, and a sad ending.', null); -- Brave, The -> Braveheart
insert into imdb_ijs.movies_recommendations values ('118980', '263', 8, 'liagolding', 'Both are grounded romantic dramas that focus on realistic character analysis and adult relationships.', null); -- Frankie and Johnny -> Til There Was You
insert into imdb_ijs.movies_recommendations values ('120506', '291698', 9, 'liagolding', 'A great detective mystery with a puzzle-like crime plot, famous actors, and a dark atmosphere.', null); -- From Hell -> Se7en
insert into imdb_ijs.movies_recommendations values ('34077', '333856', 9, 'liagolding', 'Both are epic, Hollywood dramas focusing on a long relationship with a sad ending.', null); -- Benjamin Button -> Titanic
insert into imdb_ijs.movies_recommendations values ('14477', '290070', 9, 'liagolding', 'Both are realistic historical legal dramas about survival against oppressive, cruel systems.', null); -- Amistad -> Schindler's List
insert into imdb_ijs.movies_recommendations values ('62460', '33492', 8, 'liagolding', 'Both are European-style dramas focusing on human connections, food, and clever humor.', null); -- Chocolat -> Bella Martha
insert into imdb_ijs.movies_recommendations values ('33492', '200864', 8, 'liagolding', 'Both are realistic comedies centered on working-class protagonists navigating complicated personal relationships.', null); -- Bella Martha -> Maid in Manhattan
insert into imdb_ijs.movies_recommendations values ('97360', '25192', 9, 'liagolding', 'Both are brilliant biographies about eccentric historical figures obsessed with their work.', null); -- Ed Wood -> Aviator, The
insert into imdb_ijs.movies_recommendations values ('185704', '46169', 8, 'liagolding', 'Both are intense historical dramas focusing on leadership, heavy personal stakes, and tragic ends.', null); -- Last Temptation of Christ -> Braveheart
insert into imdb_ijs.movies_recommendations values ('14157', '644', 8, 'liagolding', 'Both are light, grounded Hollywood comedies focused on high school relationships and clever humor.', null); -- American Reunion, An -> 10 Things I Hate About You
insert into imdb_ijs.movies_recommendations values ('2', '238072', 8, 'liagolding', 'Both are classic crime capers focused on a high-stakes robbery and tactical strategy.', null); -- $ 1971 -> Ocean's Eleven
insert into imdb_ijs.movies_recommendations values ('33', '306032', 8, 'liagolding', 'Both are fast-paced crime thrillers with quick dialogue and unexpected twists in the plot.', null); -- $windle 2002 -> Snatch.
insert into imdb_ijs.movies_recommendations values ('52', '271095', 8, 'liagolding', 'Both are classic action adventure movies filled with historical puzzles and physical comedy.', null); -- A gai waak 1983 -> Raiders of the Lost Ark
insert into imdb_ijs.movies_recommendations values ('108', '131780', 8, 'liagolding', 'Both are realistic crime movies focusing on law enforcement systems versus syndicate networks.', null); -- G Men 1935 -> Goodfellas
insert into imdb_ijs.movies_recommendations values ('400612', '113459', 8, 'liagolding', 'Both are realistic legal dramas focusing on courtroom strategy and analytical arguments.', null); -- Owen Marshall 1971 -> Find Me Guilty 2005
insert into imdb_ijs.movies_recommendations values ('113459', '131780', 9, 'liagolding', 'Both are realistic crime dramas based on real history with famous Hollywood stars.', null); -- Find Me Guilty 2005 -> Goodfellas
insert into imdb_ijs.movies_recommendations values ('220805', '238072', 9, 'liagolding', 'Both are fast-paced Hollywood action comedies with clever dialogue and high star power.', null); -- Mr. and Mrs. Smith 2005 -> Ocean's Eleven
insert into imdb_ijs.movies_recommendations values ('1038', '264157', 8, 'liagolding', 'Both are light, grounded comedies with famous Hollywood actresses and clever situational humor.', null); -- 13 Going On 30 2004 -> Princess Diaries 2 2004
insert into imdb_ijs.movies_recommendations values ('400853', '1038', 8, 'liagolding', 'Both are comedies centered on family relationships and relatable lifestyle complications.', null); -- Parenthood 1990 -> 13 Going On 30 2004
insert into imdb_ijs.movies_recommendations values ('379331', '263076', 8, 'liagolding', 'Both feature highly methodical investigations trying to break down a mystery with pure logic.', null); -- Sherlock Holmes 1984 -> Prescription for Murder
insert into imdb_ijs.movies_recommendations values ('112290', '210511', 10, 'liagolding', 'Excellent psychological thrillers about reality dissociation and characters with complex mental puzzles.', null); -- Fight Club -> Memento
insert into imdb_ijs.movies_recommendations values ('267038', '131780', 10, 'liagolding', 'Iconic 90s crime movies featuring realistic drama, deep character analysis, and sharp dialogue.', null); -- Pulp Fiction -> Goodfellas
insert into imdb_ijs.movies_recommendations values ('123435', '116556', 9, 'liagolding', 'Smart thrillers with a puzzle-like structure that forces you to think until the final twist.', null); -- The Game -> Following
insert into imdb_ijs.movies_recommendations values ('326155', '267038', 9, 'liagolding', 'Grounded Hollywood crime dramas focusing on intense urban character analysis and realistic grit.', null); -- Taxi Driver -> Pulp Fiction
insert into imdb_ijs.movies_recommendations values ('116556', '247579', 8, 'liagolding', 'High-tension thrillers focused on logical strategies, systems, and deep character isolation.', null); -- Following -> Panic Room
insert into imdb_ijs.movies_recommendations values ('56304', '131780', 10, 'liagolding', 'Martin Scorsese crime masterpieces sharing famous Hollywood stars, realistic drama, and criminal strategy.', null); -- Casino -> Goodfellas
insert into imdb_ijs.movies_recommendations values ('214755', '123435', 9, 'liagolding', 'Cerebral thrillers with analytical plots where characters must uncover a hidden tracking system.', null); -- Minority Report -> The Game
insert into imdb_ijs.movies_recommendations values ('290070', '297838', 10, 'liagolding', 'Powerful realistic dramas about human survival inside oppressive institutions with bittersweet endings.', null); -- Schindler's List -> Shawshank Redemption
insert into imdb_ijs.movies_recommendations values ('289109', '39551', 9, 'liagolding', 'Intense historical war dramas focusing on realistic tactical missions and heavy personal sacrifice.', null); -- Saving Private Ryan -> Black Hawk Down
insert into imdb_ijs.movies_recommendations values ('405119', '379331', 9, 'liagolding', 'Classic detective stories focusing on traditional investigative puzzles and pure deductive logic.', null); -- Sherlock Holmes 1951 -> Sherlock Holmes 1984
insert into imdb_ijs.movies_recommendations values ('306032', '238072', 9, 'liagolding', 'Clever ensemble cast with witty dialogue, complex heist strategy, and unique networks.', null); -- Snatch. -> Ocean's Eleven
insert into imdb_ijs.movies_recommendations values ('159172', '271095', 10, 'liagolding', 'The ultimate classic adventure films driven by clever historical puzzles and witty scripting.', null); -- Indiana Jones 3 -> Raiders of the Lost Ark
insert into imdb_ijs.movies_recommendations values ('328272', '113506', 8, 'liagolding', 'Grounded Hollywood dramas with top star performances, realistic character journeys.', null); -- The Terminal -> Finding Neverland
insert into imdb_ijs.movies_recommendations values ('233058', '291698', 8, 'liagolding', 'Dark crime mysteries filled with a heavy atmosphere and an analytical, puzzle-like investigation.', null); -- The Ninth Gate -> Se7en
insert into imdb_ijs.movies_recommendations values ('268034', '123435', 8, 'liagolding', 'Smart mystery thrillers with a complex plot structure and logical depth.', null); -- The Puzzle -> The Game
insert into imdb_ijs.movies_recommendations values ('164572', '267038', 9, 'liagolding', 'Clever crime films directed by Quentin Tarantino with brilliant character breakdowns and wit.', null); -- Jackie Brown -> Pulp Fiction
insert into imdb_ijs.movies_recommendations values ('118367', '306032', 8, 'liagolding', 'Ensemble comedies with fast pacing, unique situations, and very witty dialogue.', null); -- Four Rooms -> Snatch.
insert into imdb_ijs.movies_recommendations values ('130953', '312170', 9, 'liagolding', 'Classic action spy movies with iconic Hollywood style, high stakes.', null); -- Goldfinger -> Spy Who Loved Me
insert into imdb_ijs.movies_recommendations values ('311604', '300229', 8, 'liagolding', 'Animated projects with witty writing and clever parodies that appeal to adult viewers.', null); -- SpongeBob Legend Spatula -> Shrek
insert into imdb_ijs.movies_recommendations values ('287501', '335266', 8, 'liagolding', 'Grounded Israeli drama movies focusing on serious character analysis and deep personal themes.', null); -- Sanhedrin -> Tomer Ve-Hasrutim
#100 UNIQUE NOT GOOD YET REASONABLE RECOMMENDATIONS 
insert into imdb_ijs.movies_recommendations values ('30955', '30952', 2, 'liagolding', 'Both are live-action Batman movies but the second one drops the serious tone for silly jokes and campy action.', null); -- Batman -> Batman & Robin
insert into imdb_ijs.movies_recommendations values ('30955', '30965', 3, 'liagolding', 'Both are part of the original series but the second one shifts to bright colors and less interesting story writing.', null); -- Batman -> Batman Forever
insert into imdb_ijs.movies_recommendations values ('30967', '30952', 2, 'liagolding', 'Both share the same universe but the second completely loses the dark atmosphere and character depth.', null); -- Batman Returns -> Batman & Robin
insert into imdb_ijs.movies_recommendations values ('30959', '30952', 2, 'liagolding', 'Both feature the same main superhero but have completely opposite tones and script quality.', null); -- Batman Begins -> Batman & Robin
insert into imdb_ijs.movies_recommendations values ('30976', '30952', 2, 'liagolding', 'Both are 90s Batman stories but the animated one has a deep plot while the live-action one is shallow.', null); -- Batman: Mask of the Phantasm -> Batman & Robin
insert into imdb_ijs.movies_recommendations values ('30955', '30953', 2, 'liagolding', 'Both share characters but the second is a low-budget adaptation that lacks any real script strength.', null); -- Batman -> Batman & Robin 1998
insert into imdb_ijs.movies_recommendations values ('30955', '30957', 3, 'liagolding', 'Both are Batman films but the older has extremely cheap production values and thin character logic.', null); -- Batman -> Batman and Robin 1949
insert into imdb_ijs.movies_recommendations values ('30959', '30965', 3, 'liagolding', 'Both are theatrical superhero origin/stories but the writing styles and tone are completely different.', null); -- Batman Begins -> Batman Forever
insert into imdb_ijs.movies_recommendations values ('30967', '30965', 3, 'liagolding', 'Both are sequels in the same timeline but the director changed and the clever dark tone was lost.', null); -- Batman Returns -> Batman Forever
insert into imdb_ijs.movies_recommendations values ('30976', '30977', 3, 'liagolding', 'Both are animated Batman movies but the second one feels like a simple kids cartoon with less mystery depth.', null); -- Batman: Mask of the Phantasm -> Batman: Mystery of the Batwoman
insert into imdb_ijs.movies_recommendations values ('381392', '30975', 2, 'liagolding', 'Both use the same futuristic superhero setting but the second title completely lacks narrative and plot value.', null); -- Batman Beyond -> Batman: Gotham Racer
insert into imdb_ijs.movies_recommendations values ('30961', '30978', 2, 'liagolding', 'Both are animated/gaming titles from the same universe but the second has a very repetitive story structure.', null); -- Batman Beyond: Return of the Joker -> Batman: Rise of Sin Tzu
insert into imdb_ijs.movies_recommendations values ('30962', '30972', 2, 'liagolding', 'Both share the dark future theme but the second project is uninspired and lacks deep character development.', null); -- Batman Beyond: The Movie -> Batman: Dark Justice
insert into imdb_ijs.movies_recommendations values ('311037', '311040', 3, 'liagolding', 'Both are directed by Sam Raimi but the third movie is bloated with too many villains and silly subplots.', null); -- Spider-Man -> Spider-Man 3
insert into imdb_ijs.movies_recommendations values ('311038', '311040', 3, 'liagolding', 'The sequel drops the emotional depth and tight pacing of the second film for messy action and bad dialogue.', null); -- Spider-Man 2 -> Spider-Man 3
insert into imdb_ijs.movies_recommendations values ('311037', '406158', 2, 'liagolding', 'Both are Spider-Man stories from the same era but the TV spin-off lacks the big budget and smart script writing.', null); -- Spider-Man -> Spider-Man 2003
insert into imdb_ijs.movies_recommendations values ('311038', '406158', 2, 'liagolding', ' a low-budget TV animation after an excellent, grounded cinematic masterpiece feels disappointing.', null); -- Spider-Man 2 -> Spider-Man 2003
insert into imdb_ijs.movies_recommendations values ('311037', '311036', 3, 'liagolding', 'Both are early superhero projects but the older version has a very simple and dated narrative approach.', null); -- Spider-Man -> Spider-Man 2000
insert into imdb_ijs.movies_recommendations values ('313478', '313474', 3, 'liagolding', 'Both are in the same universe but the prequel replaces the dark personal stakes with boring politics and childish humor.', null); -- Star Wars: Episode V -> Star Wars: Episode I
insert into imdb_ijs.movies_recommendations values ('313479', '313476', 3, 'liagolding', 'Both are classic space films but the prequel relies too much on bad green-screen action and weak romance dialogue.', null); -- Star Wars: Episode VI -> Star Wars: Episode II
insert into imdb_ijs.movies_recommendations values ('313478', '313476', 3, 'liagolding', 'The prequel completely loses the tight dramatic pacing and excellent dialogue writing of the original trilogy.', null); -- Star Wars: Episode V -> Star Wars: Episode II
insert into imdb_ijs.movies_recommendations values ('313474', '406411', 3, 'liagolding', 'Both are prequels but the animated version focuses purely on short, repetitive combat scenes instead of character stories.', null); -- Star Wars: Episode I -> Star Wars: Clone Wars 2003
insert into imdb_ijs.movies_recommendations values ('313476', '313485', 2, 'liagolding', 'Both share the same setting but the game-based title has a thin story meant only for gameplay, not viewing value.', null); -- Star Wars: Episode II -> Star Wars: Jedi Academy
insert into imdb_ijs.movies_recommendations values ('313474', '313475', 2, 'liagolding', 'Recommending a parallel release item that repeats the exact same flawed narrative structure offers no value.', null); -- Star Wars: Episode I -> Star Wars: Episode I (Altern)
insert into imdb_ijs.movies_recommendations values ('313478', '313464', 2, 'liagolding', 'Both feature space battles but the second title is a simulation project with minimal storytelling and plot development.', null); -- Star Wars: Episode V -> Star Wars Rogue Leader
insert into imdb_ijs.movies_recommendations values ('313479', '313486', 2, 'liagolding', 'Both feature the Force but the spin-off has an unpolished, simple plot script that lacks cinematic weight.', null); -- Star Wars: Episode VI -> Star Wars: Mysteries of the Sith
insert into imdb_ijs.movies_recommendations values ('313477', '313487', 3, 'liagolding', 'Both show dark Jedi arcs but the digital spin-off simplifies the complex characters into basic action targets.', null); -- Star Wars: Episode III -> Star Wars: Jedi Outcast
insert into imdb_ijs.movies_recommendations values ('313474', '313488', 2, 'liagolding', 'Both feature pilot characters from Naboo but the secondary title has no deep character choices or story plots.', null); -- Star Wars: Episode I -> Star Wars: Jedi Starfighter
insert into imdb_ijs.movies_recommendations values ('313476', '313489', 4, 'liagolding', 'Both are sci-fi narratives but the text-heavy game adaptation has a very different rhythm that movie fans might find slow.', null); -- Star Wars: Episode II -> Star Wars: Knights of the Old Republic
insert into imdb_ijs.movies_recommendations values ('313474', '313493', 2, 'liagolding', 'Both focus on the pod-racing concept but the spin-off completely removes the character dialogue and plot development.', null); -- Star Wars: Episode I -> Star Wars: Racer Revenge
insert into imdb_ijs.movies_recommendations values ('313478', '313498', 2, 'liagolding', 'Both feature X-Wing pilots but the secondary project drops all the psychological character arcs for basic flying tasks.', null); -- Star Wars: Episode V -> Star Wars: Rogue Squadron
insert into imdb_ijs.movies_recommendations values ('313474', '313503', 2, 'liagolding', 'Both cover the same timeline but the digital adaptation replaces character decisions with endless, repetitive battle tasks.', null); -- Star Wars: Episode I -> Star Wars: The Clone Wars 2002
insert into imdb_ijs.movies_recommendations values ('313478', '313504', 3, 'liagolding', 'Both share the same name and story but the alternative release item has a less effective narrative presentation.', null); -- Star Wars: Episode V -> Star Wars: The Empire Strikes Back 1982
insert into imdb_ijs.movies_recommendations values ('313479', '313506', 2, 'liagolding', 'Both focus on fighting the Empire but the computer-based product lacks the emotional core and script pacing of the film.', null); -- Star Wars: Episode VI -> Star Wars: X-Wing
insert into imdb_ijs.movies_recommendations values ('313478', '313508', 2, 'liagolding', 'Both show space dogfights but the combat project features zero story campaign elements or character dialogue plots.', null); -- Star Wars: Episode V -> Star Wars: X-Wing vs. TIE Fighter
insert into imdb_ijs.movies_recommendations values ('130953', '354178', 3, 'liagolding', 'Both are classic Bond films but the second one features an aging lead actor, cheesy dialogue, and a very weak script.', null); -- Goldfinger -> View to a Kill
insert into imdb_ijs.movies_recommendations values ('312170', '335336', 3, 'liagolding', 'Both share the same spy action formula but the 90s movie replaces classic style and wit with generic loud explosions.', null); -- Spy Who Loved Me -> Tomorrow Never Dies
insert into imdb_ijs.movies_recommendations values ('130953', '368418', 3, 'liagolding', 'The modern sequel has a convoluted, boring plot and lacks the clever writing and iconic style of the original.', null); -- Goldfinger -> World Is Not Enough
insert into imdb_ijs.movies_recommendations values ('130945', '368418', 3, 'liagolding', 'Both star Pierce Brosnan as Bond but the second film drops the tight tension for a confusing and slow narrative.', null); -- GoldenEye -> World Is Not Enough
insert into imdb_ijs.movies_recommendations values ('130953', '218808', 3, 'liagolding', 'Both are classic era spy films but Moonraker goes too far into silly sci-fi cliches and unrealistic space battles.', null); -- Goldfinger -> Moonraker
insert into imdb_ijs.movies_recommendations values ('312170', '218808', 3, 'liagolding', 'The follow-up film moves away from clever spycraft into ridiculous sci-fi situations that damage the character logic.', null); -- Spy Who Loved Me -> Moonraker
insert into imdb_ijs.movies_recommendations values ('130953', '203649', 3, 'liagolding', 'Both are classic spy films but this entry has a highly cartoonish plot and weak action choreography compared to Goldfinger.', null); -- Goldfinger -> Man with the Golden Gun
insert into imdb_ijs.movies_recommendations values ('130945', '335336', 3, 'liagolding', 'The sequel drops the intense espionage atmosphere of GoldenEye for a generic, loud action plot with thin writing.', null); -- GoldenEye -> Tomorrow Never Dies
insert into imdb_ijs.movies_recommendations values ('92573', '218808', 2, 'liagolding', 'The franchise moves from a grounded, tense detective mystery in Dr. No to an absurd, unrealistic space fantasy in Moonraker.', null); -- Dr. No -> Moonraker
insert into imdb_ijs.movies_recommendations values ('120574', '354178', 2, 'liagolding', 'Both are Bond adventures but the 80s film lacks the smart spy pacing and tight realistic plotting of the 1963 classic.', null); -- From Russia with Love -> View to a Kill
insert into imdb_ijs.movies_recommendations values ('130953', '117314', 3, 'liagolding', 'Both are old-school Bond adventures but the 1981 film has slower pacing and a much less memorable villain setup.', null); -- Goldfinger -> For Your Eyes Only
insert into imdb_ijs.movies_recommendations values ('312170', '192514', 3, 'liagolding', 'Both feature the same lead actor but the 1973 film relies on dated genre trends that feel out of place for a spy plot.', null); -- Spy Who Loved Me -> Live and Let Die
insert into imdb_ijs.movies_recommendations values ('130945', '335337', 2, 'liagolding', 'Both are Pierce Brosnan spy titles but the secondary release item completely drains the cinematic narrative quality.', null); -- GoldenEye -> Tomorrow Never Dies 1999
insert into imdb_ijs.movies_recommendations values ('335336', '368419', 2, 'liagolding', 'The alternative digital presentation of the spy mission drops the story pacing and character interaction entirely.', null); -- Tomorrow Never Dies -> World Is Not Enough 2000
insert into imdb_ijs.movies_recommendations values ('130953', '332065', 3, 'liagolding', 'Both are Sean Connery Bond classics but Thunderball gets bogged down in very slow, repetitive underwater scenes.', null); -- Goldfinger -> Thunderball
insert into imdb_ijs.movies_recommendations values ('130945', '240521', 3, 'liagolding', 'Both are big spy missions but the 1969 film features a different lead actor who lacks the typical wit and charm.', null); -- GoldenEye -> On Her Majesty's Secret Service
insert into imdb_ijs.movies_recommendations values ('130953', '372233', 3, 'liagolding', 'The story moves away from tight spy investigations into overly large, unrealistic volcano base action sequences.', null); -- Goldfinger -> You Only Live Twice
insert into imdb_ijs.movies_recommendations values ('280270', '280305', 2, 'liagolding', 'The fifth movie completely loses the realistic human drama and heart of the original masterpiece, using cheap cliches.', null); -- Rocky -> Rocky V
insert into imdb_ijs.movies_recommendations values ('280281', '280305', 2, 'liagolding', 'The sequel switches from an inspiring, grounded sports drama to a poorly written story with a very annoying script.', null); -- Rocky II -> Rocky V
insert into imdb_ijs.movies_recommendations values ('280284', '280306', 3, 'liagolding', 'Both are late sequels but the 1986 timeline item shows severe franchise fatigue with an uninspired and slow narrative.', null); -- Rocky IV -> Rocky VI 1986
insert into imdb_ijs.movies_recommendations values ('280270', '280282', 3, 'liagolding', 'The third entry drops the raw, gritty character analysis of the original to become a commercial, flashy Hollywood show.', null); -- Rocky -> Rocky III
insert into imdb_ijs.movies_recommendations values ('280281', '280284', 3, 'liagolding', 'The fourth movie abandons realistic boxing drama for a cartoonish, over-the-top Cold War action plot with little substance.', null); -- Rocky II -> Rocky IV
insert into imdb_ijs.movies_recommendations values ('215876', '215879', 3, 'liagolding', 'The sequel drops the smart, cerebral spy puzzle and suspense of the original for mindless action tropes and explosions.', null); -- Mission: Impossible 1996 -> Mission: Impossible II
insert into imdb_ijs.movies_recommendations values ('215876', '215878', 2, 'liagolding', 'The game spin-off shares the title characters but replaces the clever script writing with repetitive, non-cinematic tasks.', null); -- Mission: Impossible 1996 -> M:I Operation Surma
insert into imdb_ijs.movies_recommendations values ('215879', '215878', 2, 'liagolding', 'Both feature the same spy hero but the interactive product lacks real story depth or interesting dialogue scenes.', null); -- Mission: Impossible II -> M:I Operation Surma
insert into imdb_ijs.movies_recommendations values ('215876', '215881', 2, 'liagolding', 'Recommending a minor promotional spoof item after a highly intense, smart Hollywood thriller offers no narrative value.', null); -- Mission: Impossible 1996 -> Mission: Improbable
insert into imdb_ijs.movies_recommendations values ('215876', '215875', 3, 'liagolding', 'The older iteration uses the title brand but lacks the modern complex plotting and high suspense of the 1996 film.', null); -- Mission: Impossible 1996 -> Mission: Impossible 1991
insert into imdb_ijs.movies_recommendations values ('215880', '215877', 3, 'liagolding', 'The 1998 alternative media product presents a very simple, dated version of the espionage team with weak writing.', null); -- Mission: Impossible III -> Mission: Impossible 1998
insert into imdb_ijs.movies_recommendations values ('300230', '300233', 2, 'liagolding', 'The short theme-park spin-off drops the clever wit and long narrative plot of Shrek 2 to focus entirely on visual gimmicks.', null); -- Shrek 2 -> Shrek 4-D
insert into imdb_ijs.movies_recommendations values ('300229', '300233', 2, 'liagolding', 'The special short feature lacks the excellent character development and sharp fairy-tale satire of the original movie.', null); -- Shrek -> Shrek 4-D
insert into imdb_ijs.movies_recommendations values ('311604', '311606', 2, 'liagolding', 'Both are animated game releases from the same franchise but the second one has an even more repetitive plot script.', null); -- SpongeBob Legend Spatula -> Revenge Flying Dutchman
insert into imdb_ijs.movies_recommendations values ('311604', '311607', 2, 'liagolding', 'Both target the same characters but use very simple, uninspired situational setups with zero narrative depth.', null); -- SpongeBob Legend Spatula -> SuperSponge
insert into imdb_ijs.movies_recommendations values ('312150', '312152', 2, 'liagolding', 'The third movie completely dumps the clever family dynamic and smart spy gadgets for a messy, ugly virtual reality plot.', null); -- Spy Kids -> Spy Kids 3-D
insert into imdb_ijs.movies_recommendations values ('312151', '312152', 2, 'liagolding', 'The sequel loses the charm and fun of the second film, becoming a lazy visual showcase with a very weak script.', null); -- Spy Kids 2 -> Spy Kids 3-D
insert into imdb_ijs.movies_recommendations values ('398571', '391006', 2, 'liagolding', 'Both are classic TV comedies but Happy Days replaces Murphy Browns sharp, witty writing with very simple sitcom tropes.', null); -- Murphy Brown -> Happy Days
insert into imdb_ijs.movies_recommendations values ('391006', '395271', 2, 'liagolding', 'This direct spin-off pushes the comedy into uninspired physical slapstick, losing the structured storytelling of the original.', null); -- Happy Days -> Laverne & Shirley
insert into imdb_ijs.movies_recommendations values ('395271', '382208', 1, 'liagolding', 'An obscure spin-off project that drains all the humor and wit, using extremely thin scripts and lazy situational cliches.', null); -- Laverne & Shirley -> Blansky's Beauties
insert into imdb_ijs.movies_recommendations values ('400853', '390691', 3, 'liagolding', 'Both show family life but Parenthood is a grounded, realistic drama while Growing Pains uses generic, predictable sitcom formulas.', null); -- Parenthood -> Growing Pains
insert into imdb_ijs.movies_recommendations values ('391006', '398232', 3, 'liagolding', 'The spin-off moves from standard retro comedy into wacky sci-fi situation humor that completely drops realistic plots.', null); -- Happy Days -> Mork & Mindy
insert into imdb_ijs.movies_recommendations values ('391006', '382208', 2, 'liagolding', 'short-lived spin-off after the highly popular main series is a bad viewing choice.', null); -- Happy Days -> Blansky's Beauties
insert into imdb_ijs.movies_recommendations values ('395271', '391453', 2, 'liagolding', 'Both are vintage situational comedies but the secondary title has a highly forgettable script and very weak character setup.', null); -- Laverne & Shirley -> Herndon
insert into imdb_ijs.movies_recommendations values ('390691', '397250', 2, 'liagolding', 'Both are family comedies but the older show relies on ridiculous, uninspired animal gimmicks instead of real dialogue.', null); -- Growing Pains -> Me and the Chimp
insert into imdb_ijs.movies_recommendations values ('271095', '159167', 3, 'liagolding', 'The long-awaited sequel drops the gritty tone and clever historical mystery for unrealistic sci-fi elements and CGI action.', null); -- Raiders -> Indiana Jones 4
insert into imdb_ijs.movies_recommendations values ('159172', '159167', 3, 'liagolding', 'The fourth film completely fails to capture the brilliant family dynamic and smart puzzle-solving of the third entry.', null); -- Indiana Jones 3 -> Indiana Jones 4
insert into imdb_ijs.movies_recommendations values ('271095', '159175', 3, 'liagolding', 'The second movie changes the clever archeological mystery tone into a much darker, meaner, and less balanced action story.', null); -- Raiders -> Indiana Jones 2
insert into imdb_ijs.movies_recommendations values ('10830', '10945', 3, 'liagolding', 'The third movie drops the intense suspense and brilliant psychological pacing of the original for a messy, depressing script.', null); -- Alien -> Alien 1992
insert into imdb_ijs.movies_recommendations values ('10920', '10945', 3, 'liagolding', 'The sequel completely ruins the action-packed excitement and great character development of the second film.', null); -- Aliens -> Alien 1992
insert into imdb_ijs.movies_recommendations values ('231917', '399427', 3, 'liagolding', 'The episodic series version loses the tight suspense discipline and smart screenwriting of the original pilot film.', null); -- Night Gallery 1969 -> Night Gallery 1970
insert into imdb_ijs.movies_recommendations values ('333856', '333849', 2, 'liagolding', 'Both tell the same tragic historical story but the old silent version lacks any modern dramatic pacing or complex writing.', null); -- Titanic 1997 -> Titanic 1915
insert into imdb_ijs.movies_recommendations values ('13396', '379931', 3, 'liagolding', 'The TV broadcast items lack the higher budget and tighter script curation of the collected theatrical anthology books.', null); -- Amazing Stories Book 1 -> Amazing Stories 1985
insert into imdb_ijs.movies_recommendations values ('13395', '379931', 3, 'liagolding', 'The general compilation has very uneven quality with several weak, uninspired episodes compared to the best volumes.', null); -- Amazing Stories Book 4 -> Amazing Stories 1985
insert into imdb_ijs.movies_recommendations values ('238072', '238073', 3, 'liagolding', 'The direct sequel dumps the smart heist planning and clever crime strategy for self-indulgent jokes and a messy plot.', null); -- Ocean's Eleven -> Ocean's Twelve
insert into imdb_ijs.movies_recommendations values ('131780', '45312', 3, 'liagolding', 'Both are crime films directed by Martin Scorsese but his early 1972 film lacks the master script writing and elite star power.', null); -- Goodfellas -> Boxcar Bertha
insert into imdb_ijs.movies_recommendations values ('267038', '118367', 3, 'liagolding', 'Both feature Quentin Tarantino but this anthology film has a very uneven, chaotic script that lacks his usual smart plotting.', null); -- Pulp Fiction -> Four Rooms
insert into imdb_ijs.movies_recommendations values ('291698', '292671', 3, 'liagolding', 'Both are dark psychological thrillers with a mystery twist but Secret Window has a much more predictable and weak ending.', null); -- Se7en -> Secret Window
insert into imdb_ijs.movies_recommendations values ('214755', '22651', 3, 'liagolding', 'Both are sci-fi thrillers starring top actors but the second film has a very slow, boring narrative with an illogical script.', null); -- Minority Report -> Astronaut's Wife
insert into imdb_ijs.movies_recommendations values ('123435', '292671', 3, 'liagolding', 'Both feature a main character caught in a puzzle plot but the second title resolves it with a very common, unoriginal cliche.', null); -- The Game -> Secret Window
insert into imdb_ijs.movies_recommendations values ('333856', '263', 3, 'liagolding', 'Both are 1997 romantic dramas but the second one is a very generic, small-scale film that entirely lacks compelling writing.', null); -- Titanic -> Til There Was You
insert into imdb_ijs.movies_recommendations values ('112290', '261532', 3, 'liagolding', 'Both link to author Chuck Palahniuk but the second item is a documentary project that lacks any of the fiction story tension.', null); -- Fight Club -> Postcards from the Future
insert into imdb_ijs.movies_recommendations values ('238072', '33', 3, 'liagolding', 'Both are modern crime capers about a tactical robbery but Swindle has a very low-budget presentation and less clever twists.', null); -- Ocean's Eleven -> $windle
insert into imdb_ijs.movies_recommendations values ('271095', '52', 3, 'liagolding', 'Both show classic retro action adventure but Project A shifts completely into martial arts physical stunts instead of smart puzzle plots.', null); -- Raiders -> A gai waak 1983
insert into imdb_ijs.movies_recommendations values ('131780', '108', 3, 'liagolding', 'Both explore gangster syndicate themes but the 1935 black-and-white film relies on obsolete, simple crime tracking formulas.', null); -- Goodfellas -> G Men 1935
insert into imdb_ijs.movies_recommendations values ('113459', '113547', 2, 'liagolding', 'Both are recent independent productions but the second short lacks any structured narrative plot or real character logic.', null); -- Find Me Guilty -> Fine Line Between Cute/Creepy
insert into imdb_ijs.movies_recommendations values ('263360', '151616', 3, 'liagolding', 'Both are high-profile commercial romantic comedies but the second one uses highly annoying, predictable genre stereotypes.', null); -- Pretty Woman -> How to Lose a Guy in 10 Days
insert into imdb_ijs.movies_recommendations values ('66194', '14132', 3, 'liagolding', 'Both are famous teen-centered comedies but American Pie 2 drops the clever, witty satire for crude, simple slapstick jokes.', null); -- Clueless -> American Pie 2
insert into imdb_ijs.movies_recommendations values ('300229', '14157', 3, 'liagolding', 'Both use adult situational comedy humor but American Reunion relies on simple nostalgia cliches instead of clever writing tricks.', null); -- Shrek -> American Reunion, An
insert into imdb_ijs.movies_recommendations values ('220805', '109421', 3, 'liagolding', 'Both are high-energy Hollywood action titles but Fast and Furious focuses purely on car racing instead of clever, witty dialogue.', null); -- Mr. and Mrs. Smith -> Fast and the Furious, The
insert into imdb_ijs.movies_recommendations values ('1038', '46878', 3, 'liagolding', 'Both are 2004 female-led comedies but the Bridget Jones sequel suffers from heavy narrative repetition and uninspired jokes.', null); -- 13 Going On 30 -> Bridget Jones: Edge of Reason
insert into imdb_ijs.movies_recommendations values ('113506', '59578', 3, 'liagolding', 'Both are stories about eccentric creative figures but the second title relies too much on weird visual CGI and a cold tone.', null); -- Finding Neverland -> Charlie and the Chocolate Factory
insert into imdb_ijs.movies_recommendations values ('25192', '59578', 3, 'liagolding', 'Both show high-budget character breakdowns of eccentric men but Johnny Depps factory title lacks realistic dramatic weight.', null); -- Aviator, The -> Charlie and the Chocolate Factory
insert into imdb_ijs.movies_recommendations values ('123849', '1121', 3, 'liagolding', 'Both are historical dramas with top stars but 1492 is a very slow, boring film with a highly unstructured script.', null); -- Gangs of New York -> 1492: Conquest of Paradise
insert into imdb_ijs.movies_recommendations values ('129185', '1121', 3, 'liagolding', 'Both are epic period historical films but the 1492 narrative completely lacks the high tension and tactical plotting of Gladiator.', null); -- Gladiator -> 1492: Conquest of Paradise
insert into imdb_ijs.movies_recommendations values ('34077', '12744', 3, 'liagolding', 'Both are fantasy-tinged romantic dramas about timeless bonds but Always is a very sentimental, predictable Spielberg film.', null); -- Benjamin Button -> Always
insert into imdb_ijs.movies_recommendations values ('97360', '97727', 4, 'liagolding', 'Both are Tim Burton/Johnny Depp collaborations but Edward Scissorhands is an unreal fairy-tale fantasy which drops realistic biography plots.', null); -- Ed Wood -> Edward Scissorhands
insert into imdb_ijs.movies_recommendations values ('185704', '230963', 3, 'liagolding', 'Both are complex dramas by Martin Scorsese but the 1977 musical entry is messy, overly long, and has unappealing character arcs.', null); -- Last Temptation of Christ -> New York, New York
insert into imdb_ijs.movies_recommendations values ('33492', '226964', 2, 'liagolding', 'Both are European comedy/dramas but the second title is an unpolished project that lacks clever writing and character substance.', null); -- Bella Martha -> Naked Laura
insert into imdb_ijs.movies_recommendations values ('350424', '215708', 2, 'liagolding', 'Both are psychological mystery titles from the same era but Missed Call relies on cheap supernatural cliches instead of a smart plot.', null); -- Vanilla Sky -> Missed Call
insert into imdb_ijs.movies_recommendations values ('207645', '214632', 2, 'liagolding', 'Both are foreign-language indie projects but the secondary title completely lacks a focused narrative line or strategy.', null); -- Matanza -> Minha Vida em Suas Mos
insert into imdb_ijs.movies_recommendations values ('361986', '322934', 2, 'liagolding', 'Both are German-language media items but the second option lacks any optical dramatic script or character conflict.', null); -- Wette, Die -> Tag der Befreiung, Der
insert into imdb_ijs.movies_recommendations values ('277945', '241620', 2, 'liagolding', 'Both are small-scale independent documentary style features but the second title has a highly repetitive and boring presentation.', null); -- Rider Pride -> One of Five
insert into imdb_ijs.movies_recommendations values ('241620', '274677', 2, 'liagolding', 'Both are short-form indie documentary projects but they completely lack cinematic tension or deep character writing.', null); -- One of Five -> Reflections of a Life
insert into imdb_ijs.movies_recommendations values ('342512', '232019', 2, 'liagolding', 'Both share a supernatural anthology focus but the second movie is a very poor B-movie project with atrocious dialogue.', null); -- Twilight Zone -> Night of a Thousand Screams
insert into imdb_ijs.movies_recommendations values ('139657', '139651', 2, 'liagolding', 'Both share the same fantasy storyline but the secondary copy lacks standard theatrical production values.', null); -- Harry Potter 1 -> Harry Potter 2 (Altern)
insert into imdb_ijs.movies_recommendations values ('194497', '194496', 2, 'liagolding', 'Both explore the same universe but the second item is a combat strategy campaign with zero film script pacing.', null); -- LOTR Fellowship -> LOTR Battle for Middle-Earth
insert into imdb_ijs.movies_recommendations values ('194497', '194501', 2, 'liagolding', 'Both are set in Middle-Earth but the interactive title completely alters character logic for gameplay targets.', null); -- LOTR Fellowship -> LOTR Third Age
insert into imdb_ijs.movies_recommendations values ('194502', '194504', 2, 'liagolding', 'The franchise changes from a high-quality cinematic puzzle drama into a repetitive, brainless digital battle simulation.', null); -- LOTR Two Towers -> LOTR War of the Ring
insert into imdb_ijs.movies_recommendations values ('194500', '194499', 2, 'liagolding', 'Recommending an alternative media bundle that strips away the dramatic narrative flow of the main trilogy offers very little value.', null); -- LOTR Return of the King -> LOTR Quest Fulfilled
insert into imdb_ijs.movies_recommendations values ('194497', '194492', 3, 'liagolding', 'The 1990 adaptation covers similar lore but uses a highly unpolished, outdated narrative technique that feels flat.', null); -- LOTR Fellowship -> Lord of the Rings 1990
